### ISSUE TITLE
Are there plans to release a version for 1.16.4

### ISSUE THREAD

**Issue by honnisha** [giovanni-bozzano/betonquest-gui#1]
I tried to compile myself, but I've got errors with func_238420_b_, idk how to fix them. Thanks!

**Comment by giovanni-bozzano** [comment]
I'm probably going to port this to 1.16.4 in the future, but I haven't yet had a chance to take a look at it.
In the meantime, the mapping for that method has probably changed. You should be able to find the new method in FontRenderer which returns the CharacterManager instance, given that the implementation hasn't changed between the two versions.

**Comment by BijuuKrunos** [comment]
Do you got time to look in this? would love to use this Mod for 1.16.5. 

Thx for your work.

**Comment by giovanni-bozzano** [comment]
> Do you got time to look in this? would love to use this Mod for 1.16.5.
> 
> Thx for your work.

I just updated the mod to 1.16.5. You can find the precompiled version in the releases section. Enjoy!
