### ISSUE TITLE
[Support request] Problem about porting this mod to 1.20.1 and running on a modded server.

### ISSUE THREAD

**Issue by Hakuyako** [giovanni-bozzano/betonquest-gui#10]
Hi there, 

I 'm trying to port the BetonQuest GUI mod and plugin to 1.20.1, and want to make it work on a modded server. 
But when I join the server, it gives an error message that the modlist doesn’t match.

![image](https://github.com/giovanni-bozzano/betonquest-gui/assets/100094927/b3661987-e745-49f8-8504-5cfcee3718ea)

Could you give me some help to make it work on a forge-bukkit server? 
Thanks a lot.

my env:
Server core: Mohist-1.20.1: https://mohistmc.com/api/v2/projects/mohist/1.20.1/builds/604/download

my port:
betonquestgui-1.20.1: https://github.com/Hypocisy/betonquest-gui
betonquestgui-plugin-1.20.1: https://github.com/Hypocisy/betonquest-gui-plugin

**Comment by zoe-may** [comment]
您好，我也遇到了相同的问题，请问有解决办法吗
