### ISSUE TITLE
Question regarding compass

### ISSUE THREAD

**Issue by Yriokiri** [giovanni-bozzano/betonquest-gui#4]
How does the compass work? how can we add quest markers to it?

**Comment by DomDL** [comment]
The quest marker tracks the same location activated by BetonQuest's compass event https://docs.betonquest.org/RELEASE/User-Documentation/Events-List/#compass-compass

**Comment by Yriokiri** [comment]
another thing since we are here. do you think is possible to add compatibility for bq 2.0 dev or is not possible at the moment? because it seems bq 1.12.9 is starting to become incompatible with some plugins.

**Comment by giovanni-bozzano** [comment]
We plan on supporting it when the stable release is out, but we may also push out a new version of the mod with support for it sooner.

**Comment by Yriokiri** [comment]
k thx for the info :D
