### ISSUE TITLE
Update for BQ 2.0

### ISSUE THREAD

**Issue by Bossbirdyman51** [giovanni-bozzano/betonquest-gui#5]
Hi ^^ It's possible to update to BetonQuest 2.0 ? Please ?
And for fabric ?

Thank you and great work ;)

**Comment by DomDL** [comment]
The mod should work with BetonQuest 2.0.0-406-DEV if you download the latest plugin release.
Maybe one day we'll update the mod to work with fabric.

**Comment by Bossbirdyman51** [comment]
> The mod should work with BetonQuest 2.0.0-406-DEV if you download the latest plugin release.
> Maybe one day we'll update the mod to work with fabric.

Okay i try it ^^ Thanks for answer and yes if you have Time to update for fabric ^^
