### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by Yriokiri** [giovanni-bozzano/betonquest-gui#7]
it seems that with the latest dev build the mod is broken, the conversations won't open anymore

mc version 1.19.2

mod version: latest
plugin version: latest

**Comment by DomDL** [comment]
Hi! We haven't tested the plugin and mod with the latest BetonQuest dev builds, are you using BQ2.0.0-DEV-526?

**Comment by Yriokiri** [comment]
Yes i'm using the latest dev build

**Comment by Yriokiri** [comment]
any news on this?

**Comment by DomDL** [comment]
I update the plugin to the latest dev version: BQ2.0.0-547.
You can download it here: https://github.com/giovanni-bozzano/betonquest-gui-plugin/releases/tag/v1.1.0-BQ2.0.0-547-DEV.
